---
title: "OWRS Analysis"
output: html_notebook
---

```{r, echo=FALSE}
library(dplyr)
library(ggplot2)
library(scales)
library(raster)
library(RateParser)
library(yaml)
library(purrr)
```


```{r, echo=FALSE}
source("R/utils.R")
source("R/plots.R")


#Declare the customer classes to be tested for each utility
customer_classes <- c("RESIDENTIAL_SINGLE"
                      #"RESIDENTIAL_MULTI",
                      #"COMMERCIAL"
)
#End

#import sample data and give the data parameters used in the owrs files that are not in the original data
df_smc <- santamonica
names(df_smc) <- c( "cust_id", "usage_ccf", "usage_month", "usage_year",  "cust_class", "usage_date", "cust_class_from-utility")

df_sample <- tbl_df(df_smc) %>%
  mutate(hhsize = 4, meter_size = '3/4"', usage_zone = 1, landscape_area = 2000,
         et_amount = 2.0, wrap_customer = "No", irr_area = 2000, carw_customer = "No",
         season = "Winter", tax_exemption = "granted", lot_size_group = 3,
         temperature_zone = "Medium", pressure_zone = 1, water_font = "city_delivered",
         area = "inside_city", water_type = "potable", rate_class = "C1",
         dwelling_units = 10, elevation_zone = 2, greater_than = "False",
         usage_indoor_budget_ccf = .3, meter_type = "compound", block = 1,
         tariff_area = 1, turbine_meter = "No", senior = "no") %>%
  group_by(cust_class)

df_adjustable_sample <- tbl_df(data.frame (usage_month = 7, days_in_period = 30,
                                           hhsize = 4, meter_size = '3/4"', usage_zone = 1, landscape_area = 2000,
                                           et_amount = 7.0, wrap_customer = "No", irr_area = 2000, 
                                           carw_customer = "No", season = "Winter", tax_exemption = "granted", 
                                           lot_size_group = 3, temperature_zone = "Medium", pressure_zone = 1, 
                                           water_font = "city_delivered", city_limits = "inside_city", 
                                           water_type = "potable", rate_class = "C1", dwelling_units = 10, 
                                           elevation_zone = 2, greater_than = "False", usage_indoor_budget_ccf = .3, 
                                           meter_type = "Turbine", block = 1, tariff_area = 1, turbine_meter = "No",
                                           senior = "no", cust_class = customer_classes[1]))

#change for The scatter plots (If start = end the process will be a lot faster if only concerned with histograms and bar/pie charts)
start <- 0;
end <- 10;
interval <- 5;
df_usage <- as.data.frame(list("usage_ccf"=1:10, "cust_class"="RESIDENTIAL_SINGLE"))
df_sample <-  left_join(df_usage, df_adjustable_sample, by="cust_class")



#Retrieve the directories and files in the directores from the Open-Water-Specification-File directory
owrs_path <- "../Open-Water-Rate-Specification/full_utility_rates/California";

#TODO insert the filename gathering functioon here
df_OWRS <- tbl_df(as.data.frame(list("filepath"=getFileNames(owrs_path)), stringsAsFactors=FALSE)) %>% 
  
  mutate(owrs_directory = map(filepath, strsplit, split="/") %>% map(c(1,1))) %>%
  
  mutate(filename = map(filepath, strsplit, split="/") %>% map(c(1,2))) %>%
  
  mutate(utility_id = map(owrs_directory, strsplit, split=" ") %>%  
                      map(1) %>%map(tail, n=1) %>%
                      map(gsub, pattern="\\D", replacement="") %>%
                      map(as.numeric)) %>%
  
  mutate(effective_date = sapply(filename, extract_date) ) %>% 
  mutate(utility_name = sapply(as.character(owrs_directory), extract_utility_name) )


df_bill <- calculate_bills_for_all_utilities(df_OWRS, df_sample, owrs_path, customer_classes)

#Format the Bill Information so that only valid data entries are presented, the decimal points are rounded, and the data is arranged by utility
df_final_bill <- tbl_df(df_bill) %>% filter(!is.na(bill)) %>%
  mutate(bill = round(as.numeric(bill), 2),
         commodity_charge = round(as.numeric(commodity_charge), 2),
         service_charge = round(service_charge, 2),
         utility_name = as.character(utility_name),
         bill_frequency = as.character(bill_frequency),
         usage_ccf = ifelse(unit_type=="kgal", 1.33681*usage_ccf, usage_ccf)) %>% 
  arrange(utility_name)
#End
```

```{r}
#library(rgdal)

#shape <- readOGR(dsn = "../Shapefiles", layer = "service_areas_cadc_with_utility_id")
#shape <- merge(shape, df_final_bill, by = "utility_id")

#setwd("../../Dropbox/CSV/")
#Output The Final Bill information to a  shapefile
#writeOGR(shape, ".", "service_areas_cadc_with_billing_info", driver="ESRI Shapefile", overwrite_layer = TRUE)
#End
#zipDemFiles <- list.files(recursive = TRUE)
#setwd("../")
#zip(zipfile = "../Dropbox/CSV/shapefileZip", files = paste("TempShapeFiles", zipDemFiles, sep = "/"))

#setwd("../../Documents/WaterRateTester/")
```

```{r}
#The usage_ccf to evaluate for the histograms and bar chart
singleTargetValue <- 10;
```

```{r}
plot_bill_frequency_piechart(df_final_bill)
```

```{r}
plot_mean_bill_pie(df_final_bill, singleTargetValue)
```



```{r}
plot_rate_type_pie(df_final_bill)
```

```{r}
plot_commodity_charges_vs_usage(df_final_bill, start, end, interval)
```

```{r}
plot_bills_vs_usage(df_final_bill, start, end, interval)
```



meanpercentFixed <- round(mean(as.numeric(df_final_bill$percentFixed[df_final_bill$usage_ccf == singleTargetValue])), 3)


```{r}
plot_ratio_histogram(df_final_bill, singleTargetValue)
```

```{r}
plot_bill_histogram(df_final_bill, singleTargetValue)
```

